services:
  - type: web
    name: Socket-Chat-server
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true